// Generated by Selenium IDE

import core.selenium.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class CalculatorSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;

  public String getValue (){
    String value = driver.findElement(By.name("expr")).getAttribute("value");
    return value;
  }
  @Before
  public void setUp() {
    driver = WebDriverManager.getInstance().getWebDriver();
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aditiontest() {
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.linkText("+")).click();
    driver.findElement(By.linkText("4")).click();
    driver.findElement(By.linkText("=")).click();
    {
      assertThat(getValue(), is("5"));
    }
  }
  @Test
  public void divitiontest() {
    driver.findElement(By.linkText("8")).click();
    driver.findElement(By.linkText("÷")).click();
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.linkText("=")).click();
    {
      assertThat(getValue(), is("4"));
    }
  }
  @Test
  public void multiplicationtest() {
    driver.findElement(By.linkText("5")).click();
    driver.findElement(By.linkText("×")).click();
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.linkText("=")).click();
    {
      assertThat(getValue(), is("10"));
    }
  }
  @Test
  public void substractiontest() {
    driver.findElement(By.linkText("6")).click();
    driver.findElement(By.linkText("-")).click();
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.linkText("=")).click();
    {
      assertThat(getValue(), is("5"));
    }
  }
}
